### ISSUE TITLE
aggregate 'QPainterPath path' has incomplete type and cannot be defined

### ISSUE THREAD

**Issue by plops** [BatchDrake/SuWidgets#9]
I tried to compile with qt 5.15.1 and had errors like this:

```
g++ -c -pipe -O2 -std=gnu++1y -Wall -Wextra -D_REENTRANT -fPIC -D_SU_SINGLE_PRECISION -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I/usr/local/include/sigutils -I/usr/local/include/sigutils/util -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -Irelease -I/usr/include/libdrm -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o release/moc_Waterfall.o release/moc_Waterfall.cpp
Histogram.cpp: In member function 'void Histogram::drawHistogram()':
Histogram.cpp:350:18: error: aggregate 'QPainterPath path' has incomplete type and cannot be defined
  350 |     QPainterPath path;
      |                  ^~~~
```
Compilation succeeded after I added this line to Histogram.cpp, Wavefrom.cpp, and LCD.cpp:
`
#include <QPainterPath>`

**Comment by BatchDrake** [comment]
Hi, thank you for reporting this one! This is failing in `master`, right? This one is fixed in `develop` but somehow I forgot to merge this change back to `master`. Do you mind sending me a pull request with your changes? 

PS: If you are building SigDigger for your personal use, you may want to build all 4 projects (sigutils, suscan, SuWidgets and SigDigger) from `develop` instead. `develop` has tons of bugfixes and new features and is way closer to 0.2.0 than `master`.

Thanks!
